/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort_reg.h"                // include port register header file

IfxCpu_syncEvent g_cpuSyncEvent = 0;

#define P0_BIT_LSB_IDX                0
#define P1_BIT_LSB_IDX                1
#define P2_BIT_LSB_IDX                2

#define PC0_BIT_LSB_IDX               3
#define PC1_BIT_LSB_IDX               11
#define PC2_BIT_LSB_IDX               19

/*
 * register setup for ulstrasonic sensor and UART
 *
 *
 *
 */



void init_GPIO(void){
    P00_IOCR0.U &= ~(0x1F << PC0_BIT_LSB_IDX);
    P00_IOCR0.U &= ~(0x1F << PC1_BIT_LSB_IDX);
    P00_IOCR0.U &= ~(0x1F << PC2_BIT_LSB_IDX);

    P00_IOCR0.U |= (0x10 << PC0_BIT_LSB_IDX);       // PORT00 PIN0 as output (Fault monitor to ECU2)
    P00_IOCR0.U |= (0x02 << PC1_BIT_LSB_IDX);       // PORT00 PIN1 as input with pull up (Fault monitor from ECU1, 0: No fault(= blocked) 1:Fault(= not blocked))
    P00_IOCR0.U |= (0x10 << PC2_BIT_LSB_IDX);       // PORT00 PIN2 as output (Warning trigger to  ECU3)
}

/*
 * initialization function for ultrasonic sensor
 *
 * void init_ultrasonicSensor(void){
 *
 * blah blah
 *
 * }
 */

/*
 * initialization function for UART
 *
 * void init_UART(void){
 *
 * blah blah
 *
 * }
 */

/*
 * activation function for ultrasonic sensor
 *
 * void ultrasonicScan(void){
 *
 *
 * Fault = 0 or 1;
 *
 */

/*
 * activation function for readUART
 *
 * unsigned int readUART(void){
 *
 *
 *     return target_raw;
 *
 */

/*
 * activation function for writeUART
 *
 * void writeUART(int){
 *
 *
 *
 */


/*
 * activation function for ultrasonic sensor
 *
 * void ultrasonicScan(void){
 *
 *
 * ECU_fault = 0 or 1;
 *
 */


int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    


    // glabal variable
    char ECU_Fault = 0;
    unsigned int target_raw = 0;
    unsigned int target_1 = 0;
    /*
     * init_ultrasonicSensor();
     * init_UART();
     *
     */
    init_GPIO();

    while(1)
    {

        target_raw = readUART();
        ultrasonicScan();
        if (ECU_Fault == 1){
            target_1 = 0;
            P00_OUT.U &= ~(1 << P0_BIT_LSB_IDX);  //set port00 pin0 Low in case of fault
        }
        else {
            target_1 = target_raw;
            P00_OUT.U |= (1 << P0_BIT_LSB_IDX);  //set port00 pin0 high in case of no fault
        }

        if (P00_IN.U & (1 << P1_BIT_LSB_IDX) == 0){   //ECU2 is in fault state

            P00_OUT.U &= ~(1 << P2_BIT_LSB_IDX);  //set port00 pin2 low in case of fault
        }
        else{
            P00_OUT.U |= (1 << P2_BIT_LSB_IDX);  //set port00 pin2 high in case of no fault
        }

        writeUART(target_1);


    }
    return (1);
}
